/**
 * Possible deployment status responses.
 */
export const DeploymentStatus = Object.freeze({
	UPLOADED: "UPLOADED",
	DEPLOYED: "DEPLOYED",
	DEPLOY_FAILED_UNKNOWN: "DEPLOY_FAILED_UNKNOWN",
	DEPLOY_FAILED_MISSING_VERSION: "DEPLOY_FAILED_MISSING_VERSION",
	UNKNOWN_STARTED: "UNKNOWN_STARTED",
	START_FAILURE: "START_FAILURE",
	STOPPED: "STOPPED",
	STOP_FAILURE: "STOP_FAILURE",
	UNKNOWN_STOPPED: "UNKNOWN_STOPPED",
	HEALTH_CHECK_OK: "HEALTH_CHECK_OK",
	HEALTH_CHECK_FAILURE: "HEALTH_CHECK_FAILURE",
	INVALID_REQUEST: "INVALID_REQUEST"
});
