domino:
  registrations-path: config/domino-registrations.yml
  logfile: logs/domino.log
  storage:
    enable-upload: true
    accepted-mime-types:
      - application/java-archive
    max-size: 100MB
    path: storage/
  server:
    host: localhost
    port: 9987
  service-handler: systemd
  start-timeout: 3000
  auth:
    expiration: "30 days"
    jwt-private-key: <PROVIDE_ME>
    username: <PROVIDE_ME>
    password: <PROVIDE_ME>
