services:

  # main dependencies
  app.main:
    class: 'domino/DominoApplication'
    arguments: [
      '@web.component.registrations',
      '@app.express'
    ]
  app.express:
    factory:
      class: 'domino/web/factory/ExpressApplicationFactory'
      method: 'createExpressApplication'

  # core layer
  # components
  core.component.registrations.factory:
    class: 'domino/core/registration/AppRegistrationsFactory'

  core.component.registrations.registry:
    class: 'domino/core/registration/AppRegistrationRegistry'
    arguments: ['@core.component.registrations.factory']

  # web layer
  # components
  web.component.registrations:
    class: 'domino/web/ControllerRegistrations'
    arguments: [
      '@web.component.factory.multer',
      '@web.controller.upload'
    ]

  web.component.factory.multer:
    class: 'domino/web/factory/ExpressMulterFactory'
    arguments: ['@core.component.registrations.registry']

  # controllers
  web.controller.upload:
    class: 'domino/web/controller/UploadController'
